name: "Setup Environment"
description: "Sets up the environment with C++ compiler, CMake, and dependencies"
runs:
  using: "composite"
  steps:
    - name: Set up C++ Compiler
      uses: aminya/setup-cpp@v1
      with:
        compiler: gcc

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29.0'

    - name: Install dependencies
      run: |
        set -eo pipefail
        sudo apt-get update
        sudo apt-get install -y zlib1g-dev=1:1.2.11* zlib1g=1:1.2.11*
      shell: bash
