name: Build, Test, and Install Verification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.13.0
        with:
          clang-format-version: '16'
          check-path: '.'

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Configure CMake
        run: cmake -S . -B build -DTINYVTU_WITH_TESTS=ON

      - name: Build with CMake
        run: cmake --build build

      - name: Run tests with CTest
        run: ctest --test-dir build --output-on-failure

  build_and_install:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Configure CMake
        run: cmake -S . -B build -DTINYVTU_WITH_TESTS=OFF

      - name: Build with CMake
        run: cmake --build build

      - name: Install the library
        run: cmake --install build --prefix /tmp/tinyvtu_install

      - name: Verify building example project
        run: |
          mkdir examples_build
          cd examples_build
          cmake -DCMAKE_PREFIX_PATH=/tmp/tinyvtu_install ../examples
          cmake --build .

      - name: Verify running example project
        working-directory: examples_build
        run: |
          if [ ! -f "./example_tetra" ]; then
            echo "Example binary not found"
            exit 1
          fi
          ./example_tetra || {
            echo "Example execution failed"
            exit 1
          }
